services:
  frontend_api:
    container_name: frontend-api
    image: frontend-api
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    environment:
      - TTS_API=http://text_to_speech:8003
      - TEXT_EXTRACTION_API=http://text_extraction:8001
    volumes:
      - frontend_logs:/app/logs
    networks:
      - app_network
    healthcheck:
      test: curl --fail http://localhost:3009 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  text_to_speech:
    container_name: text-to-speech
    image: text-to-speech
    build:
      context: ./text_to_speech
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
        - TTS_SERVER=http://tts_server:80
    volumes:
      - tts_logs:/app/logs
    networks:
      - app_network
    healthcheck:
      test:  curl --fail http://text_to_speech:8003/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  text_extraction:
    container_name: text_extraction
    image: text-extraction
    build:
      context: ./text_extraction
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
        - CONVERTER_API=http://converter:5000
    depends_on:
      - converter
    volumes:
      - text_extraction_logs:/app/logs
    networks:
      - app_network
    healthcheck:
      test:  curl --fail http://text_extraction:8001/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  converter:
    container_name: converter
    image: converter
    build:
      context: ./converter
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - converter_uploads:/app/uploads
      - converter_outputs:/app/outputs
    networks:
      - app_network
    healthcheck:
      test: curl --fail http://converter:5000/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  tts_server:
    container_name: xtts-stream
    image: xtts-stream
    build:
      context: ./tts_server
      dockerfile: Dockerfile
    environment:
      COQUI_TOS_AGREED: "1"  # Required by Coqui TTS
    ports:
      - "8000:80"
    runtime: nvidia  # Enables GPU support with NVIDIA runtime
    restart: unless-stopped
    volumes:
      - tts_server_models:/app/tts_models
    networks:
      - app_network
    healthcheck:
      test:  curl --fail http://tts_server:80/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  tts_server_models:
    driver: local
  frontend_logs:
    driver: local
  tts_logs:
    driver: local
  text_extraction_logs:
    driver: local
  converter_uploads:
    driver: local
  converter_outputs:
    driver: local

networks:
  app_network:
    driver: bridge