services:
  frontend_api:
    container_name: frontend-api
    image: frontend-api
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    depends_on:
      - text_to_speech
      - text_extraction
      - converter
      - tts_server
    environment:
      - TTS_API=http://text_to_speech:8003/tts
      - SPEAKER_API=http://text_to_speech:8003/studio_speakers
      - TEXT_EXTRACTION_API=http://text_extraction:8001/process
      - CONVERTER_API=http://converter:5000/convert
    volumes:
      - frontend_logs:/app/logs

  text_to_speech:
    container_name: text-to-speech
    image: text-to-speech
    build:
      context: ./text_to_speech
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - tts_server
    volumes:
      - tts_logs:/app/logs

  text_extraction:
    container_name: text-extraction
    image: text-extraction
    build:
      context: ./text_extraction
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - converter
    volumes:
      - text_extraction_logs:/app/logs

  converter:
    container_name: converter
    image: converter
    build:
      context: ./converter
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - converter_uploads:/app/uploads
      - converter_outputs:/app/outputs

  tts_server:
    container_name: xtts-stream
    image: xtts-stream
    build:
      context: ./tts_server
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      COQUI_TOS_AGREED: "1"  # Required by Coqui TTS
    ports:
      - "8000:80"
    runtime: nvidia  # Enables GPU support with NVIDIA runtime
    restart: unless-stopped
    volumes:
      - tts_server_models:/app/tts_models

volumes:
  tts_server_models:
    driver: local
  frontend_logs:
    driver: local
  tts_logs:
    driver: local
  text_extraction_logs:
    driver: local
  converter_uploads:
    driver: local
  converter_outputs:
    driver: local
