services:
  frontend_api:
    container_name: frontend-api
    image: frontend-api
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    environment:
      - CONVERTER_API=http://converter:5000
      - XTTS_SERVER_API=http://tts_server:80
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app_network
    depends_on:
      tts_server:
        condition: service_healthy
#      redis:
#        condition: service_started
    healthcheck:
      test: curl --fail http://localhost:3009 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  converter:
    container_name: converter
    image: converter
    build:
      context: ./converter
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - converter_uploads:/app/uploads
      - converter_outputs:/app/outputs
    networks:
      - app_network
    healthcheck:
      test: curl --fail http://converter:5000/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  tts_server:
    container_name: xtts-stream
    image: xtts-stream
    build:
      context: ./tts_server/TTS
      dockerfile: Dockerfile
    environment:
      COQUI_TOS_AGREED: "1"  # Required by Coqui TTS
    ports:
      - "8000:80"
    runtime: nvidia  # Enables GPU support with NVIDIA runtime
    restart: unless-stopped
    volumes:
      - tts_server_models:/app/tts_models
      - tts_logs:/app/logs
      - tts_outputs:/app/outputs
    networks:
      - app_network
    healthcheck:
      test: curl --fail http://tts_server:80/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

#  redis:
#    container_name: redis
#    image: redis:latest
#    restart: unless-stopped
#    ports:
#      - "6379:6379"
#    networks:
#      - app_network

volumes:
  tts_server_models:
    driver: local
  tts_logs:
    driver: local
  tts_outputs:
    driver: local
  converter_uploads:
    driver: local
  converter_outputs:
    driver: local

networks:
  app_network:
    driver: bridge
